import { DEFAULT_POSE, type JointPose } from './joints'

export const POSES = {
  stand: { ...DEFAULT_POSE },
  idleA: {
    ...DEFAULT_POSE,
    torso: 2,
    upperArmL: 14,
    upperArmR: -14,
    head: 3,
  },
  idleB: {
    ...DEFAULT_POSE,
    torso: -2,
    upperArmL: 6,
    upperArmR: -6,
    head: -2,
  },
  crouch: {
    ...DEFAULT_POSE,
    rootY: 12,
    torso: 8,
    upperLegL: 35,
    lowerLegL: -55,
    upperLegR: 35,
    lowerLegR: -55,
    upperArmL: 25,
    upperArmR: -25,
  },
  jumpPeak: {
    ...DEFAULT_POSE,
    rootY: -55,
    upperArmL: -140,
    upperArmR: 140,
    upperLegL: -15,
    lowerLegL: -20,
    upperLegR: 15,
    lowerLegR: -20,
  },
  star: {
    ...DEFAULT_POSE,
    // Arms diagonal up-and-out (not overhead); same outward sense as legs.
    upperArmL: 100,
    upperArmR: -100,
    lowerArmL: 0,
    lowerArmR: 0,
    upperLegL: 40,
    upperLegR: -40,
    lowerLegL: 0,
    lowerLegR: 0,
  },
  tuck: {
    ...DEFAULT_POSE,
    torso: 20,
    head: 15,
    upperArmL: -40,
    lowerArmL: -90,
    upperArmR: 40,
    lowerArmR: 90,
    upperLegL: 70,
    lowerLegL: -120,
    upperLegR: 70,
    lowerLegR: -120,
  },
  tuckSpin: {
    ...DEFAULT_POSE,
    rootRot: 360,
    torso: 20,
    head: 15,
    upperArmL: -40,
    lowerArmL: -90,
    upperArmR: 40,
    lowerArmR: 90,
    upperLegL: 70,
    lowerLegL: -120,
    upperLegR: 70,
    lowerLegR: -120,
  },
  waveUp: {
    ...DEFAULT_POSE,
    // Right arm out to the side (negative = outward); forearm flaps for the wave.
    upperArmR: -90,
    lowerArmR: -55,
    head: 8,
  },
  waveDown: {
    ...DEFAULT_POSE,
    upperArmR: -85,
    lowerArmR: -15,
    head: 4,
  },
  split: {
    ...DEFAULT_POSE,
    rootY: 15,
    upperLegL: -80,
    lowerLegL: 0,
    upperLegR: 80,
    lowerLegR: 0,
    upperArmL: 40,
    upperArmR: -40,
  },
  moonwalk1: {
    ...DEFAULT_POSE,
    upperLegL: 20,
    lowerLegL: 0,
    upperLegR: -30,
    lowerLegR: -30,
    upperArmL: 20,
    upperArmR: -40,
  },
  moonwalk2: {
    ...DEFAULT_POSE,
    upperLegL: -30,
    lowerLegL: -30,
    upperLegR: 20,
    lowerLegR: 0,
    upperArmL: -40,
    upperArmR: 20,
  },
  backflipTuck: {
    ...DEFAULT_POSE,
    rootY: -60,
    rootRot: -180,
    torso: 30,
    head: 20,
    upperArmL: -60,
    lowerArmL: -100,
    upperArmR: 60,
    lowerArmR: 100,
    upperLegL: 90,
    lowerLegL: -130,
    upperLegR: 90,
    lowerLegR: -130,
  },
  backflipLand: {
    ...DEFAULT_POSE,
    rootRot: -360,
    rootY: 15,
    torso: 15,
    upperLegL: 40,
    lowerLegL: -60,
    upperLegR: 40,
    lowerLegR: -60,
    upperArmL: 30,
    upperArmR: -30,
  }
} as const satisfies Record<string, JointPose>

export type PoseId = keyof typeof POSES
